# -*- coding: utf-8 -*-
"""Mumbai_home_pred_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOkOg58-fOqFlKUUNztm-WEyX8gkwvH2
"""



import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

model = joblib.load("Mumbai_home_pred.pkl")
encoder = joblib.load("label_encoder_home.pkl")

st.title("Mumbai Home Price Prediction")

price = st.number_input("Price")
area = st.number_input("Area")
price_per_sqft = st.number_input("Price per sqft")
locality = st.selectbox("Locality",encoder["locality"].classes_)
city = st.selectbox("City",encoder["city"].classes_)
property_type = st.selectbox("Property Type",encoder["property_type"].classes_)
bedroom_num = st.number_input("bedroom_num")
bathroom_num = st.number_input("bathroom_num")
balcony_num = st.number_input("balcony_num")
furnished = st.selectbox("Furnished",encoder["furnished"].classes_)
age = st.number_input("Age")
total_floors = st.number_input("total_floors")
latitude = st.number_input("Latitude")
longitude = st.number_input("Longitude")


df = pd.DataFrame({
    "Price":[price],
    "Area":[area],
    "Price per sqft":[price_per_sqft],
    "Locality":[locality],
    "City":[city],
    "Property Type":[property_type],
    "Bedroom number":[bedroom_num],
    "No.of.Bathroom":[bathroom_num],
    "No.of.Balcony":[balcony_num],
    "Furnished":[furnished],
    "Age":[age],
    "Total Floor":[total_floors],
    "Latitude":[latitude],
    "Longitude":[longitude]

})

if st.button("Predict Mumbai Home Price"):
  for column in encoder:
    df[column] == encoder[column].transform(df[column])

  prediction = model.predict(df)
  st.success(f"The predicted price is {prediction}")
